# Scaffolding generated by Casein v5.1.1.5

module Casein
  class HomeImagesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Home images'
  		@home_images = HomeImage.order(sort_order(:photo_url)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View home image'
      @home_image = HomeImage.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new home image'
    	@home_image = HomeImage.new
    end

    def create
      @home_image = HomeImage.new home_image_params
    
      if @home_image.save
        flash[:notice] = 'Home image created'
        redirect_to casein_home_images_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new home image'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update home image'
      
      @home_image = HomeImage.find params[:id]
    
      if @home_image.update_attributes home_image_params
        flash[:notice] = 'Home image has been updated'
        redirect_to casein_home_images_path
      else
        flash.now[:warning] = 'There were problems when trying to update this home image'
        render :action => :show
      end
    end
 
    def destroy
      @home_image = HomeImage.find params[:id]

      @home_image.destroy
      flash[:notice] = 'Home image has been deleted'
      redirect_to casein_home_images_path
    end
  
    private
      
      def home_image_params
        params.require(:home_image).permit(:photo_url, :link_url)
      end

  end
end